// <auto-generated />
using System;
using InstitucionEducativaGenerica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InstitucionEducativaGenerica.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250913180658_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InstitucionEducativaGenerica.Models.Student", b =>
                {
                    b.Property<int>("idStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_student");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idStudent"));

                    b.Property<DateTime>("birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("student_birthday");

                    b.Property<int>("course")
                        .HasColumnType("integer")
                        .HasColumnName("student_course");

                    b.Property<string>("studentMail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_mail");

                    b.Property<string>("studentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_name");

                    b.Property<string>("studentPs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_ps");

                    b.HasKey("idStudent");

                    b.ToTable("students", "school0001a");
                });
#pragma warning restore 612, 618
        }
    }
}
